### ISSUE TITLE
All MQTT fields should follow the state of the Enabled toggle

### ISSUE THREAD

**Issue by obones** [cpainchaud/rflink-webui#11]
In the MQTT page, the toggle at the top controls the enabling or disabling of text fields in the page, thus preventing us from editing the values if it is turned off.
However, the last three fields are always enabled which feels a bit strange.

I would personally prefer if fields would not follow the state of the "Enabled" toggle, allowing me to enter values even if they are not used. But if the Enabled toggle is to control the enabled/disabled status of other controls on the page, it should control all of them, not just a part of them.

**Comment by TheStaticTurtle** [comment]
Was it the ssl fields?

**Comment by obones** [comment]
![image](https://user-images.githubusercontent.com/1314739/110324545-6cec6680-8016-11eb-8430-113e02d0e858.png)

The three fields at the bottom

**Comment by TheStaticTurtle** [comment]
Issue related to #8, fields were not in definitions.js
