### ISSUE TITLE
The Home page does not display the DNS server retrieved via DHCP

### ISSUE THREAD

**Issue by obones** [cpainchaud/rflink-webui#13]
When I go to the home tab, I see the IP that was obtained via DHCP for the RFLink module.
However, the DNS server is not shown, despite the fact that the DHCP server sends it properly (other devices use it, and a wireshark trace shows it)

**Comment by TheStaticTurtle** [comment]
Can you provide a screenshot?
It should be there, is it just empty ?

**Comment by cpainchaud** [comment]
it prints unknow, it's a backend issue. my task !!!

**Comment by obones** [comment]
yes, exactly, it's there, but says "unknown". 
Wasn't sure where the issue was coming from though.

**Comment by cpainchaud** [comment]
fixed here : https://github.com/cpainchaud/RFLink/commit/07fa76ed84aae53eb80a80fe08d4a21c1c086f29
