### ISSUE TITLE
Disabling an item will hide input field but not the input name

### ISSUE THREAD

**Issue by cpainchaud** [cpainchaud/rflink-webui#19]
see screenshot

![image](https://user-images.githubusercontent.com/6696638/110615605-e362a300-8193-11eb-9423-c4fba2eef8a9.png)

**Comment by TheStaticTurtle** [comment]
These field should only be grayed out. Which browser are you using?
I tested on chrome(mobile and desktop), firefox(mobile and desktop), edge, safari and they all work fine

**Comment by cpainchaud** [comment]
chrome :D
