### ISSUE TITLE
Add support for Signal configurations

### ISSUE THREAD

**Issue by cpainchaud** [cpainchaud/rflink-webui#2]
from data structure in commit https://github.com/cpainchaud/rflink-webui/commit/ce03f8d9d5391c5ed5f7b304c3227d2b37ef818f

**Comment by TheStaticTurtle** [comment]
Resolved by: 235ccf2b379dcb0f42b026e1e3ab48d746a52a8e, 64d630e7db0ea00c3215c4f791c4073685a507cc, 9c0cd325a7506c196feece23daa020a89977a8be
