### ISSUE TITLE
In the summary, the border is different if the cell is empty

### ISSUE THREAD

**Issue by obones** [cpainchaud/rflink-webui#25]
Have a look at this capture:

![image](https://user-images.githubusercontent.com/1314739/114144566-c269ab00-9915-11eb-860d-e133b0b07686.png)

As you can see, the border at the top right and bottom right are black instead of gray. I believe this is because the cells are empty

**Comment by TheStaticTurtle** [comment]
As it's only the outer border I'm more thinking that it's the form that is missing the border because all cells / rows should have their border set to the grey color.
I'll look into it more later today

**Comment by TheStaticTurtle** [comment]
This is due to the values not being sent by the api (or not received correctly idk I'm using the mock for testing). This results in the <td> not being created at all applying a border to the <tr> solves the issue I'll push the changes later tonight
